# Generated by Django 3.1 on 2020-08-24 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200824_1809'),
        ('games_ratings', '0003_auto_20200824_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesratings',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
