# Generated by Django 3.1 on 2020-08-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_ratings', '0004_auto_20200825_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesratings',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
